<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="/assets/styles/style.css" media="screen"/>
    <title>Oops ! Page introuvable !</title>
</head>
<body>
    <main>
        <section>
            <h1>
               Erreur 404
            </h1>

            <article class="card-404">

                <h2>404</h2>
                <h3>Oops ! Page introuvable ! </h3>


                <a href="/home">Retourner sur le site</a>
            </article>


        </section>
    </main>
</body>
</html>