<?php
// Vérifier si l'utilisateur est connecté
$isLoggedIn = isset($_SESSION['user']);

// Génération et stockage du jeton CSRF dans la session
if (!isset($_SESSION['csrf_token'])) {
    try {
        $_SESSION['csrf_token'] = bin2hex(random_bytes(32));
    } catch (Exception $e) {
        // En cas d'échec de génération, ne définissez pas le jeton ou affichez un message d'erreur approprié
        $_SESSION['csrf_token'] = ''; // Peut-être afficher un message d'erreur à l'utilisateur
    }
}
?>

<?php if ($isLoggedIn): ?>
    <!-- Contenu pour les utilisateurs connectés -->
    <section id="section-main-admin">
        <h1>HELLO WORLD</h1>
        <a href="/logout">Logout</a>
    </section>
<?php else: ?>
    <!-- Contenu pour les utilisateurs non connectés -->
    <section id="section-connexion">
        <section id="img-home"></section>
        <section id="card-connexion">
            <div id="container-connexion">
                <form action="/connexion" name="auth-form" method="POST">
                    <fieldset>
                        <h2>Connexion</h2>
                        <input type="hidden" name="csrf_token" value="<?= htmlspecialchars($_SESSION['csrf_token'] ?? '', ENT_QUOTES, 'UTF-8') ?>">

                        <label for="email">E-mail :</label>
                        <input type="email" id="email" name="email" required>

                        <label for="password">Mot de passe :</label>
                        <input type="password" id="password" name="password" required>

                        <input class="btn-connexion" type="submit" value="Se Connecter">

                        <a href="/register">Inscription</a>
                    </fieldset>
                </form>
            </div>
        </section>
    </section>
<?php endif; ?>
