<section id="section-header">
    <a id="logo-container" href="/connexion">
        <img class="logo" src="/./assets/images/logo.webp" alt="logo page admin">
    </a>

    <nav id="nav-container">
        <ul class="nav-list">
            <li><a href="https://guillaume-ledan.fr" class="active">Aller sur le site</a></li>
            <li><a href="/logout">Déconnexion</a></li>
        </ul>
    </nav>
</section>
